### ISSUE TITLE
Feature Request: manual IP settings

### ISSUE THREAD

**Issue by JrtPec** [flukso/flm-ui#2]
It would be nice if you could manually assign a static IP-address through the interface.

**Comment by gebhardm** [comment]
To prevent inconsistent static IP provisioning within a DHCP based setup this feature I would always see at the DHCP server side. I use to provide a static IP address to my FLMs on the router. That prevents me from having to change devices on router alterations (e.g. subnet change); this may not be applicable where not access to the DHCP setup is granted - but then the subnet change may also prevent access to the FLM in the first place. Thus, this may be more a process issue than a software change request.

**Comment by icarus75** [comment]
I agree with Markus on allocating client IPs in the DHCP server. Better still, the FLM uses bonjour/avahi mDNS to advertise its services in the LAN. You can thus reach any FLM in the local network via its hostname. Look it up on the local configuration status page and add a ```.local``` suffix. It should then have this form: ```flukso-xxxxxx.local```. No more twiddling with IP stuff needed.
