### ISSUE TITLE
Incorrectly set wireless encryption for new routers

### ISSUE THREAD

**Issue by gebhardm** [flukso/flm-ui#3]
In https://github.com/flukso/flm-ui/blob/master/app/scripts/controllers/wifi.js#L80 the encryption is set hard coded; this on using new routers runs into the issue that encryption "psk-mixed" is too "unspecific"; in my case I had to set it explicitly to "psk2+tkip+ccmp"; maybe the detected encryption can be provided "as is"?

Ref to issue https://github.com/flukso/flm02/issues/8

**Comment by icarus75** [comment]
A psk-mixed indicates wpa/wpa2 availability. Could you do a quick re-testing with encryption set to "psk-mixed+tkip+ccmp" on the FLM?

**Comment by gebhardm** [comment]
Performed following commands:

     root@flukso-c13f30:~# uci show | grep psk  
     wireless.@wifi-iface[0].encryption=psk2+tkip+ccmp 
     root@flukso-c13f30:~# uci set wireless.@wifi-iface[0].encryption=psk-mixed+tkip+ccmp
     root@flukso-c13f30:~# uci show | grep psk
     wireless.@wifi-iface[0].encryption=psk-mixed+tkip+ccmp
     root@flukso-c13f30:~# uci commit
     root@flukso-c13f30:~# uci show | grep psk
     wireless.@wifi-iface[0].encryption=psk-mixed+tkip+ccmp
     root@flukso-c13f30:~# /etc/init.d/network restart

...and lost my wifi connection :-(

**Comment by gebhardm** [comment]
Switching back to psk2+tkip+ccmp brought up the wpa_supplicant instantly.

**Comment by icarus75** [comment]
Hmmmm. Could you run following command on your FLM an post the output of your router's BSS:
```root@flukso-69f187:~# iw dev wlan0 scan```

**Comment by gebhardm** [comment]
I'll send it by email instantly.

**Comment by gebhardm** [comment]
Function send2encrypt retrieves "psk-mixed+tkip+ccmp" - ap.encryption.wpa is 3.

**Comment by icarus75** [comment]
So just storing the detected encryption type is a no go for your setup.

**Comment by gebhardm** [comment]
On getting no connect I used the OpenWRT docu to figure out what to do; an 

    iwinfo

brought the information that my router uses following setup:

root@flukso-c13f30:~# iwinfo
     wlan0     ESSID: "UPCxxxxxxx"
          Access Point: xx:xx:xx:xx:xx:xx
          Mode: Client  Channel: 1 (2.412 GHz)
          Tx-Power: 20 dBm  Link Quality: 42/70
          Signal: -68 dBm  Noise: -109 dBm
          Bit Rate: 54.0 MBit/s
          Encryption: WPA2 PSK (TKIP, CCMP)
          Type: nl80211  HW Mode(s): 802.11bg
          Hardware: unknown [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes
...and with WPA2 PSK  I was lead to psk2... I don't know why, but this works

**Comment by icarus75** [comment]
My best guess is that your router advertises itself as supporting wpa/wpa2 modes, but in fact only allows the latter.

**Comment by icarus75** [comment]
wpa_supplicant seems smart enough to figure out the encryption itself. Could you double-check whether the following works correctly in your setup:
1/ comment out lines 75 and 79 in /lib/wifi/wpa_supplicant.sh
2/ use the local web interface to save the wifi config once more
I expect this to work on your system, despite the encryption being set to "psk-mixed".

**Comment by gebhardm** [comment]
Will check in the evening and report back.

**Comment by gebhardm** [comment]
I commented out the proto lines, saved the wifi config from the UI - and lost wifi again :-(
Then even manually resetting the encryption and restarting the network did not bring up the wpa_supplicant. So, uncommented the proto lines again.

**Comment by icarus75** [comment]
Ok, let's debug the supplicant. Can you create following config file at `/root/wpa_supplicant-wlan0.conf` (with proper substitutions for YourAP and YourKey):
```
ctrl_interface=/var/run/wpa_supplicant-wlan0
network={
	scan_ssid=1
	ssid="YourAP"
	key_mgmt=WPA-PSK
	psk="YourKey"
}
```
Then kill the running wpa_supplicant process and run:
```
wpa_supplicant -P /var/run/wifi-wlan0.pid -D nl80211 -i wlan0 -c /root/wpa_supplicant-wlan0.conf -dd
```
Add the trace to this thread or send it via mail. Whichever you prefer.

**Comment by gebhardm** [comment]
That is interesting; with the above configuration provided and the wifi data saved via the web UI (psk-mixed), the connection can be established normally:

Successfully initialized wpa_supplicant
wlan0: SME: Trying to authenticate with 54:67:51:07:e1:35 (SSID='ssid' freq=2412 MHz)
wlan0: Trying to associate with 54:67:51:07:e1:35 (SSID='ssid' freq=2412 MHz)
wlan0: Associated with 54:67:51:07:e1:35
wlan0: WPA: Key negotiation completed with 54:67:51:07:e1:35 [PTK=CCMP GTK=TKIP]
wlan0: CTRL-EVENT-CONNECTED - Connection to 54:67:51:07:e1:35 completed [id=0 id_str=]

uci show provides now:
wireless.@wifi-iface[0]=wifi-iface
wireless.@wifi-iface[0].device=radio0
wireless.@wifi-iface[0].network=wan
wireless.@wifi-iface[0].mode=sta
wireless.@wifi-iface[0].key=<pwd>
wireless.@wifi-iface[0].ssid=<ssid>
wireless.@wifi-iface[0].encryption=psk-mixed

A reboot yet leaves the wireless still unconnected even though ps states that the wpa_supplication is started
618 root      1656 S    wpa_supplicant -B -P /var/run/wifi-wlan0.pid -D nl80

Killing this and rerunning the wpa_supplicant call from above again reconnects - strange.

/etc/init.d/network restart  fails; setting encryption to psk2, and a restart works :-~

Just had a look at the syslog (command dmesg) - and this reports

[   47.570000] wlan0: associating with AP with corrupt probe response

Now the "Preisfrage" is "corrupted" with respect to a 2006 network shell script or just "unknown" as the specification evolved?! Be it as it is, it seems as if the wpa_supplicant acts correctly, while the /etc/network and /sbin/wifi scripts of the OpenWRT installation behave differently than expected; as noted, this happens with routers supplied this year. So I expect rather not "corruption" but "evolution" in specification...

**Comment by icarus75** [comment]
Just for clarity's sake: If you start the supplicant manually as per my previous comment, the FLM associates with the AP. Is this action consistent? I.e. does this succeed every time you launch the supplicant manually?

The failure to associate after a reboot seems normal to me, as the supplicant will start up as a daemon, pointing to a dynamically generated config file instead of the manual one we defined. The same could be the case for the network restart. Please verify the latter.

**Comment by gebhardm** [comment]
Issue solved if protocol is forced to "proto='proto=WPA RSN'" in psk section of file /lib/wifi/wpa_supplicant.sh
